micronaut:
  application:
    name: demo
r2dbc:
  datasources:
    default:
      schema-generate: CREATE_DROP
      dialect: POSTGRES
      db-type: postgres
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        connection:
          db-type: postgres
    reactive: true
